{{- if  and  (eq (include "prometheus.enabled" .) "true")  (.Values.prometheus.server_enabled) (.Values.prometheus.grafana.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasources
  namespace: {{ template "monitoring.namespace" . }}
data:
  all.yaml: |-
    datasources:
    - name: 'Prometheus'
      type: 'prometheus'
      access: 'proxy'
      org_id: 1
      url: 'http://{{ .Values.prometheus.servicename }}:{{ .Values.prometheus.serviceport }}'
      is_default: true
      version: 1
      editable: true
{{- end }}
---
{{- if  and  (eq (include "prometheus.enabled" .) "true")  (.Values.prometheus.server_enabled) (.Values.prometheus.grafana.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboards
  namespace: {{ template "monitoring.namespace" . }}
data:
  all.yaml: |-
    - name: 'dash1'
      org_id: 1
      folder: ''
      type: 'file'
      options:
        folder: '/var/lib/grafana/'
{{- end }}

