{
 "title": "Kubernetes SP metrics",
 "description": "Monitors Kubernetes deployments in cluster using Prometheus. Shows overall cluster CPU / Memory of deployments, replicas in each deployment. Uses Kube state metrics and cAdvisor metrics ",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "SP deployment total  memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (container_memory_working_set_bytes{container_label_io_kubernetes_pod_name=~\"enterprisedb-deployment.*|sd-sp.*|sd-ui.*\"}))/ sum (machine_memory_bytes{kubernetes_io_hostname=~\".*\"}) * 100"
    }
   ]
  },
  {
   "title": "SP deployment  total  CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_name=~\"enterprisedb-deployment.*|sd-sp.*|sd-ui.*\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\".*\"}) * 100"
    }
   ]
  },
  {
   "title": "SP Replicas Available",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n(sum(kube_deployment_status_replicas_available{deployment=~\"sd-sp.*\"} OR on() vector(0) )\n+ sum(kube_statefulset_status_replicas_ready{statefulset=~\"sd-sp.*\"} OR on() vector(0) ))\n/\n(sum(kube_statefulset_status_replicas{statefulset=~\"sd-sp.*\"} OR on() vector(0) ) \n+ sum(kube_deployment_status_replicas{deployment=~\"sd-sp.*\"} OR on() vector(0) ) )\n) *100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container_label_io_kubernetes_pod_name=~\"enterprisedb-deployment.*|sd-sp.*|sd-ui.*\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "machine_memory_bytes{kubernetes_io_hostname=~\".*\"}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_name=~\"enterprisedb-deployment.*|sd-sp.*|sd-ui.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\".*\"})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "\nsum(kube_deployment_status_replicas_available{deployment=~\"sd-sp.*\"} OR on() vector(0) )\n+ sum(kube_statefulset_status_replicas_ready{statefulset=~\"sd-sp.*\"} OR on() vector(0) )\n\n"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_statefulset_status_replicas{statefulset=~\"sd-sp.*\"} OR on() vector(0) ) \n+ sum(kube_deployment_status_replicas{deployment=~\"sd-sp.*\"} OR on() vector(0) ) )\n"
    }
   ]
  },
  {
   "title": "SP Global Deployment CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",container_label_io_kubernetes_pod_name=~\"enterprisedb-deployment.*|sd-sp.*|sd-ui.*\"}[1m])) ",
     "legendFormat": "{{ SP pods }}"
    }
   ]
  },
  {
   "title": "SP Containers CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",io_kubernetes_container_name!=\"POD\",container_label_io_kubernetes_pod_name=~\"sd-sp.*\"}[1m])) by (io_kubernetes_container_name, container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{ container_label_io_kubernetes_pod_name}}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name!~\"^k8s_.*\",container_label_io_kubernetes_pod_name=~\"sd-sp.*\"}[1m])) by (pod_name, name, image)",
     "legendFormat": "docker: {{ pod_name }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{rkt_container_name!=\"\",container_label_io_kubernetes_pod_name=~\"sd-sp.*\"}[1m])) by (pod_name, rkt_container_name)",
     "legendFormat": "rkt: {{ pod_name }} | {{ rkt_container_name }}"
    }
   ]
  },
  {
   "title": "All SP containers CPU usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",container_label_io_kubernetes_pod_name=~\"enterprisedb-deployment.*|sd-sp.*|sd-ui.*\"}[1m])) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{ container_label_io_kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "SP global deployment  memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_label_io_kubernetes_pod_name=~\"enterprisedb-deployment.*|sd-sp.*|sd-ui.*\"})",
     "legendFormat": "{{ Memory usage }}"
    }
   ]
  },
  {
   "title": "All SP containers memory usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",container_label_io_kubernetes_pod_name=~\"enterprisedb-deployment.*|sd-sp.*|sd-ui.*\"}) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{ container_label_io_kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "SP global deployment network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",container_label_io_kubernetes_pod_name=~\"enterprisedb-deployment.*|sd-sp.*|sd-ui.*\"}[1m])) ",
     "legendFormat": "-> {{ Total Input }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",container_label_io_kubernetes_pod_name=~\"enterprisedb-deployment.*|sd-sp.*|sd-ui.*\"}[1m])) ",
     "legendFormat": "<- {{ Total output }}"
    }
   ]
  },
  {
   "title": "SP all processes network I/O",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{container_label_io_kubernetes_pod_name=~\"enterprisedb-deployment.*|sd-sp.*|sd-ui.*\"}[1m])) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "-> {{ container_label_io_kubernetes_pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{container_label_io_kubernetes_pod_name=~\"enterprisedb-deployment.*|sd-sp.*|sd-ui.*\"}[1m])) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "<- {{ container_label_io_kubernetes_pod_name }}"
    }
   ]
  }
 ]
}