{
 "title": "SA Self Monitoring metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Nodes offline",
   "type": "gauge",
   "description": "Number of times a SA node has been offline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "nodes_offline", "legendFormat": "{{data_message}}" }
   ]
  },
  {
   "title": "Workflow threshold surpased",
   "type": "graph",
   "description": "Current work list length has exceeded the set threshold ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workflows_threshold{{data_length}}",
     "legendFormat": "{{data_length}}"
    }
   ]
  },
  {
   "title": "Heap memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(sm_heap_memory_bytes{job=~\"sqlexporter\"} ) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Non heap memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(sm_non_heap_memory_bytes{job=~\"sqlexporter\"} ) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Worker threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(sm_worker_threads{job=~\"sqlexporter\"} ) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Activation threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(sm_activation_threads{job=~\"sqlexporter\"} ) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Activation queue size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(sm_activation_queue{job=~\"sqlexporter\"} ) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Total jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(sm_total_jobs{job=~\"sqlexporter\"} ) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "User sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(sm_user_sessions{job=~\"sqlexporter\"} ) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}